controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_action_controller:
      type: gripper_action_controller/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_1:
        trajectory: 0.05
        goal: 0.03
      joint_2:
        trajectory: 0.05
        goal: 0.03
      joint_3:
        trajectory: 0.05
        goal: 0.03
      joint_4:
        trajectory: 0.05
        goal: 0.03
      joint_5:
        trajectory: 0.05
        goal: 0.03
      joint_6:
        trajectory: 0.05
        goal: 0.03

gripper_action_controller:
  ros__parameters:
    joints:
      - joint_6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_stalling: false

    goal_tolerance: 0.01

    max_effort: 5.0

    open_action_name: ~/open
    close_action_name: ~/close

    max_open_position: 0.0
    min_closed_position: -0.7 